#!/bin/sh

info=$(wmctrl -l | grep "Discord")

if [ "$info" -eq "" ]
then
    discord
else
    index=$(wmctrl -l | grep "Discord"   | awk '{print $2}')
    ws=$(wmctrl -d    | grep "$index  -" | awk '{print $9}')
    i3-msg workspace $ws
fi