#!/bin/sh

current_theme=$(tail -n 1 ./palettes/mocha.scss)

if [ "$current_theme" = "// DARK" ]
then
    cp ./palettes/mocha-light.scss ./palettes/mocha.scss    
else 
    cp ./palettes/mocha-dark.scss  ./palettes/mocha.scss
fi