#!/bin/sh

names=("" "" "" "" "" "" "" "" "" "")

# Busco como se llama cada workspace activo
wmctrl -d | awk '{print $1 " " $9}' > /tmp/d.txt
while read  -r index name; do
	# Para cada indice, guardo su nombre
	names[$index]=$name
done < /tmp/d.txt

titles=("" "" "" "" "" "" "" "" "" "")

# Busco como se llama cada ventana activa
wmctrl -l > /tmp/l.txt
while read line; do

	# Busco el titulo de la ventana
	long_title=$(echo "$line" | cut -d' ' -f5-)
	# Busco el indice de la ventana
	index=$(echo "$line" | cut -d' ' -f3)

	# Según qué ventana tengo, guardo el nombre corto en su ws (segun el nombre del ws)
	if [[ $long_title == *"Vivaldi"* ]]; then
		titles[names[$index]]+="v"
	elif [[ $long_title == *"Sublime"* ]]; then
		titles[names[$index]]+="s"
	elif [[ $long_title == *"Discord"* ]]; then
		titles[names[$index]]+="d"
	elif [[ $long_title == *"Telegram"* ]]; then
		titles[names[$index]]+="t"
	else
		titles[names[$index]]="*"
	fi

done < /tmp/l.txt

echo [ \"${titles[0]}\", \"${titles[1]}\", \"${titles[2]}\", \"${titles[3]}\", \"${titles[4]}\", \"${titles[5]}\", \"${titles[6]}\", \"${titles[7]}\", \"${titles[8]}\", \"${titles[9]}\"]

# if contains Vivaldi  print "v"
# if contains Sublime  print "s"
# if contains Zathura  print "z"
# if contains Discord  print "d"
# if contains Telegram print "t"
# if contains files    print "e"
# if contains Kitty    print "k"