#!/bin/sh

screen_extended=$(tail -n 1 /tmp/screen_extended)

if [ "$screen_extended" = "false" ]
then

	# Activo modo extend screen
	echo "true" >> /tmp/screen_extended

	eww open dock-monitor

	xrandr --auto --output HDMI-1 --mode 1366x768 --left-of eDP-1
	xrandr --auto --output eDP-1  --mode 1366x768
	
	feh --bg-fill Pictures/akko-violeta.jpg

else 
	
	# Activo modo mirror
	echo "false" >> /tmp/screen_extended
	eww close dock-monitor
	xrandr --fb 1366x768 --output eDP-1 --mode 1366x768 --scale-from 1366x768 --output HDMI-1 --mode 1366x768 --scale 1x1 --same-as eDP-1

fi